server:
  port: 8087
  servlet:
    context-path: /api/authorization
management:
  server:
    port: 8187
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: authorization
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: authorization-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret: my-512-bit-secret-32-characters-long-mySecretJWTToken-bank192837465-authorization
  expiration-ms: 86400000           # 24 часа
logging:
  level:
    root: INFO
    com.bank.authorization: DEBUG
logging.level.org.springframework.security: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
